id = "oceanic-next-darker"
name = "Oceanic Next Theme (Darker)"
version = "0.4.0"
schema_version = 1
authors = ["Rosen Kanev <rkunev@gmail.com> & rmnbrd"]
description = "Minimalist dark theme, a port of the popular Oceanic Next with slight changes."
repository = "https://github.com/rmnbrd/oceanic-next"
